---
- hosts: localhost
  connection: local
  become: True

  vars_files:
    #- 'local_settings.yml'
    - './vars/main.yml'

  roles:
    - role: packages
      tags: packages
    - role: users
      tags: users
    - role: docker
      tags: docker
    - role: jenkins
      tags: jenkins
    - role: kubernetes
      tags: kubernetes
    - role: nginx
      tags: nginx

