---
- hosts: jenkins
  connection: local
  become: True

  vars_files:
    #- 'local_settings.yml'
    - './vars/users.yaml'

  roles:
    - role: packages
      tags: packages
    - role: users
      tags: users
    - role: docker
      tags: docker
    - role: jenkins
      tags: jenkins
    - role: kubernetes
      tags: kubernetes
    - role: nginx
      tags: nginx
    - role: mail
      tags: mail

  # Can't decide where to put this
  # so putting it here for now
  tasks:
    - name: Set supervisor configuration
      template:
        src: "templates/{{ item }}"
        dest: "/etc/supervisor/conf.d/{{ item }}"
        group: root
        owner: root
        mode: 0600
      with_items:
        - docker-registry-eu-west.conf
        - docker-registry-us-west.conf
      notify: Restart supervisor
      tags:
        - supervisor

  handlers:
    - name: Restart supervisor
      service:
        name: supervisor
        state: restarted
      become_user: root

